version: 2
updates:
  - package-ecosystem: "uv"
    cooldown:
      default-days: 10 # Fallback cooldown if no specific rule applies
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys-api-speos"
        - "ansys-sphinx-theme"
        - "ansys-tools-common"
        - "ansys-tools-visualization-interface"
        - "ansys-platform-instancemanagement"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Europe/Paris"
    labels:
      - "maintenance"
      - "dependencies"
    assignees:
      - "StefanThoene"
      - "pluAtAnsys"
      - "echambla"
      - "jomadec"
    ignore:
      - dependency-name: "grpcio-tools"
      - dependency-name: "grpcio-health-checking"
    commit-message:
      prefix: "build(uv)"
    groups:
      core-deps:
        patterns:
          - "ansys-tools-common"
          - "numpy"
          - "comtypes"
      grpc-deps:
        patterns:
          - "grpc*"
          - "protobuf"
      doc-deps:
        patterns:
          - "ansys-sphinx-theme*"
          - "jupytext"
          - "jupyterlab"
          - "jupyter-server"
          - "myst-parser"
          - "nbconvert"
          - "nbsphinx"
          - "numpydoc"
          - "sphinx"
          - "sphinx*"
      test-deps:
        patterns:
          - "pytest*"
      graphics-deps:
        patterns:
          - "pyvista"
          - "ansys-tools-visualization-interface"
      jupyter-deps:
        patterns:
          - "jupyterlab"
          - "ipywidgets"
          - "notebook"
          - "matplotlib"

  - package-ecosystem: "github-actions"
    cooldown:
      default-days: 10 # Fallback cooldown if no specific rule applies
      include:
        - "*"  # Include all dependencies in cooldown
      exclude:
        - "ansys/actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "Europe/Paris"
    labels:
      - "maintenance"
    assignees:
      - "StefanThoene"
      - "pluAtAnsys"
      - "echambla"
      - "jomadec"
    commit-message:
      prefix: "build(ci)"