version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
    assignees:
      - "pyansys-ci-bot"
    ignore:
      - dependency-name: "grpcio-tools"
      - dependency-name: "grpcio-health-checking"
    commit-message:
      prefix: "build"
    groups:
      grpc-deps:
        patterns:
          - "grpc*"
          - "protobuf"
      doc-deps:
        patterns:
          - "ansys-sphinx-theme*"
          - "jupytext",
          - "jupyterlab",
          - "jupyter-server",
          - "myst-parser"
          - "nbconvert"
          - "nbsphinx"
          - "numpydoc"
          - "sphinx"
          - "sphinx*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns:
          - "*"