version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "grpcio-tools"
      - dependency-name: "grpcio-health-checking"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "MAINT"
    groups:
       grpc-deps:
          patterns:
            - "google*"
            - "grpc*"
            - "protobuf"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
