Documentation:
- any-glob-to-any-file: [doc/source/**/*]
Maintenance:
- any-glob-to-any-file: ['.github/**/*', '.flake8', 'ignore_words.txt']
Dependencies:
- any-glob-to-any-file: [requirements/*]
CI/CD:
- any-glob-to-any-file: [.github/**/*]