ci:
  # Commit name when auto fixing PRs.
  autofix_commit_msg: |
    ci: auto fixes from pre-commit.com hooks.

    for more information, see https://pre-commit.ci

  autoupdate_commit_msg: 'ci: pre-commit autoupdate'
  autoupdate_schedule: weekly

exclude: |
    (?x)(
        ^tests/assets/
    )

repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.10
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    args: ["--ignore-words", "doc/styles/config/vocabularies/ANSYS/accept.txt", "-w"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

# This validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.0
  hooks:
    - id: check-github-workflows

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.5.2
  hooks:
    - id: add-license-headers
      files: '(ansys|tests)/.*\.(py)'
      args:
      - --start_year=2021