exclude: |
    (?x)(
        ^tests/assets/
    )
repos:


- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    args:
      - --line-length=140

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort

- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args:
      - --max-line-length=140

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.5
  hooks:
  - id: codespell
    args: ["--ignore-words=ignore_words.txt", "doc/styles/vocab/ANSYS/accept.txt"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

# this validates our github workflow files
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.23.2
  hooks:
    - id: check-github-workflows

# - repo: https://github.com/pycqa/pydocstyle
#   rev: 6.1.1
#   hooks:
#   - id: pydocstyle
#     files: ^pyspeos/
#     args: ["--ignore=D205,D100,D213"]
#     additional_dependencies: [toml]

- repo: https://github.com/asottile/blacken-docs
  rev: 1.14.0
  hooks:
  -   id: blacken-docs
      additional_dependencies: [black==23.3.0]


- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.2.9
  hooks:
    - id: add-license-headers
      files: '(ansys|examples|tests)/.*\.(py)'
      args:
      - --start_year=2023