version: "3.4"
services:
  speos-rpc:
    image: ghcr.io/ansys-internal/speos-rpc:2025.1.1.25031
    container_name: speos-rpc
    ports:
      - "50051:50098"
    environment:
      - SPEOS_LOG_LEVEL=2
      - ANSYSLMD_LICENSE_FILE=$LICENSE_SERVER
    entrypoint: /app/SpeosRPC_Server.x
    volumes:
      - type: bind
        source: ./tests/assets
        target: /app/assets
        read_only: false
      - type: bind
        source: ./tests/jupyter_notebooks
        target: /app/jupyter_notebooks
        read_only: false