version: "3.4"
services:
  pyoptics_speos-rpc:
    image: ghcr.io/pyansys/pyoptics/speos-rpc
    container_name: pyoptics_speos-rpc
    ports:
      - "50051:50051"
    entrypoint: ./SpeosRPC_Server.x