version: "3.4"
services:
  optics_speos-rpc:
    image: ghcr.io/pyansys/pyoptics/speos-rpc:2023.2.0.578
    container_name: optics_speos-rpc
    ports:
      - "50051:50051"
    environment:
      - SPEOS_LOG_LEVEL=2
      - ANSYSLMD_LICENSE_FILE=$LICENSE_SERVER
    entrypoint: /app/SpeosRPC_Server.x
    volumes:
      - type: bind
        source: ./tests/assets
        target: /app/assets
        read_only: false
