[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
# Check https://flit.readthedocs.io/en/latest/pyproject_toml.html for all available sections
name = "ansys-speos-core"
version = "0.1.dev0"
description = "A Python wrapper for Ansys Speos"
readme = "README.rst"
requires-python = ">=3.8"
license = {file = "LICENSE"}
authors = [
    {name = "ANSYS, Inc.", email = "pyansys.support@ansys.com"},
]
maintainers = [
    {name = "PyAnsys developers", email = "pyansys.maintainers@ansys.com"},
]
classifiers=[
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Private :: Do Not Upload",
]
dependencies=[
    "grpcio==1.59.3",
    "grpcio-tools==1.48.2",
    "grpcio-health-checking==1.48.2",
    "ansys-api-speos==0.4.0",
]

[project.optional-dependencies]
tests = [
    "pytest==7.4.2",
    "ansys-platform-instancemanagement>=1.0.3",
    "pytest-cov==4.1.0",
]
doc = [
    "ansys-sphinx-theme==0.12.5",
    "numpydoc==1.6.0",
    "Sphinx==7.2.6",
    "sphinx-copybutton==0.5.2",
]

[tool.flit.module]
name = "ansys.speos.core"

[project.urls]
Source = "https://github.com/ansys-internal/pyspeos"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 100
default_section = "THIRDPARTY"
src_paths = ["doc", "src", "tests"]

[tool.coverage.run]
source = ["ansys.speos.core"]

[tool.coverage.report]
show_missing = true