[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
# Check https://flit.readthedocs.io/en/latest/pyproject_toml.html for all available sections
name = "ansys-speos"
version = "0.1.dev0"
description = "A Python wrapper for Ansys Speos"
readme = "README.rst"
requires-python = ">=3.9"
license = {file = "LICENSE"}
authors = [
    {name = "ANSYS, Inc.", email = "pyansys.support@ansys.com"},
]
maintainers = [
    {name = "PyAnsys developers", email = "pyansys.maintainers@ansys.com"},
]
classifiers=[
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Private :: Do Not Upload",
]
dependencies=[
    "protobuf>=3.20,<6",
    "grpcio==1.66.1",
    "grpcio-health-checking==1.48.2",
    "ansys-api-speos==0.6.0",
    "numpy~=2.0.0",
    "pyvista==0.44.1",
    "comtypes==1.4.6",
]

[project.optional-dependencies]
tests = [
    "pytest==8.3.2",
    "ansys-platform-instancemanagement>=1.0.3",
    "pytest-cov==5.0.0",
]
jupyter = [
    "matplotlib",
    "jupyterlab>=3",
    "ipywidgets",
    "pyvista[jupyter]",
]
doc = [
    "ansys-sphinx-theme==0.16.6",
    "numpydoc==1.8.0",
    "Sphinx==7.4.7",
    "sphinx-copybutton==0.5.2",
    "sphinx-autoapi==3.2.1",
    "sphinx_design==0.6.1",
    "sphinx-jinja==2.0.2",
]
app = [
    "PySimpleGUI==5.0.4",
]

[tool.flit.module]
name = "ansys.speos"

[project.urls]
Source = "https://github.com/ansys-internal/pyspeos"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 100
default_section = "THIRDPARTY"
src_paths = ["doc", "src", "tests", "app"]

[tool.coverage.run]
source = ["ansys.speos.core", "ansys.speos.script", "ansys.speos.workflow"]

[tool.coverage.report]
show_missing = true