# Copyright (C) 2021 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Check the file formats against the reference files published by Ansys.

Round-trip tests cannot catch a mistake made symmetrically in the reader and in the
writer. The files in ``tests/assets/input_files`` were produced by Speos and attached to
the Ansys Optics knowledge base articles describing each format, so they pin the layout
independently from our own implementation:

* ``Non-Scattering.material``, ``Henyey-Greenstein.material``,
  ``Double Henyey-Greenstein.material``, ``Gegenbauer.material`` and
  ``User-Defined.material`` come from the Speos Scattering and Non-Scattering Volume
  Format articles.
* ``Coating Example.coated`` comes from the Speos Coating Surface Format article.
* ``KB.spectrum`` comes from the Create spectrum file from graph article.
* ``Gold.material`` and ``Birefringent SellMeier.material`` are the metallic and
  birefringent samples attached to the review of the file format support.
* the two ``*.OPT3DMapping`` files come from the ``3DTexture_Data.7z`` archive of the
  Homogeneous 3D Texture via Scripting article, and were generated by Speos itself.

Each test states what the article says the file holds, then checks that reading it gives
exactly that, and that writing the model back reproduces the original lines.
"""

from inspect import signature

import pytest

from ansys.speos.core import (
    CoatedSurfaceFile,
    CoatedSurfaceSample,
    MaterialBirefringentSellmeier,
    MaterialDispersionCurve,
    MaterialFile,
    MaterialMetallicCurve,
    MaterialSellmeier,
    Ray,
    RayFile,
    ScatteringSurfaceFile,
    ScatteringSurfaceSample,
    SimpleScatteringSurfaceFile,
    SpectrumFile,
    Texture3DMappingFile,
    TexturePattern,
    VolumeScatteringDoubleHenyeyGreenstein,
    VolumeScatteringGegenbauer,
    VolumeScatteringHenyeyGreenstein,
    VolumeScatteringUserDefined,
)
from ansys.speos.core.input_files._base import SpeosFileFormat, _property_name, _ValueComparable
from tests.input_files import ASSETS_DIR, read_lines

REFERENCE_DIR = ASSETS_DIR / "input_files"
"""Directory holding the reference files attached to the knowledge base articles."""

SHARED_DISPERSION = MaterialDispersionCurve(
    wavelengths=[486.0, 532.0, 643.0], indices=[2.0, 1.5, 1.2]
)
"""Index curve shared by every reference material file."""

SHARED_ABSORPTION = ([400.0, 550.0, 700.0], [0.1, 0.2, 0.01])
"""Absorption curve shared by every reference material file, in nm and mm-1."""

SHARED_DIFFUSION = ([486.0, 532.0, 643.0], [0.016813, 7.3952e-17, 0.017344])
"""Diffusion curve shared by every scattering reference material file, in nm and mm-1."""


def normalize(line):
    """Drop the ``.0`` that some Speos versions append to a format version.

    The samples attached to the articles are stamped ``OPTIS - Material file v13.0`` and
    ``OPTIS - Volumic Scattering file v1.0``, while the 2026 R1 User Material editor
    writes ``v13`` and ``v1`` for the very same content.
    """
    stripped = line.rstrip()
    if stripped.startswith("OPTIS - ") and stripped.endswith(".0"):
        return stripped[:-2]
    return stripped


def assert_written_back_unchanged(model, tmp_path, reference):
    """Check that writing the model reproduces the lines of the reference file.

    Blank lines, trailing whitespace and the format version are ignored, since Speos is
    not consistent about any of them.
    """
    written = model.save(tmp_path / reference.name)
    expected = [normalize(line) for line in read_lines(reference) if line.strip()]
    actual = [normalize(line) for line in read_lines(written) if line.strip()]

    assert actual == expected


def material_with(scattering=None):
    """Build the reference material, optionally carrying a scattering phase function."""
    absorption_wavelengths, absorption_values = SHARED_ABSORPTION
    description = "Example file to understand Speos {} file structure".format(
        "scattering" if scattering else "non-scattering"
    )
    material = MaterialFile(
        description=description,
        dispersion=SHARED_DISPERSION,
        absorption_wavelengths=absorption_wavelengths,
        absorption_values=absorption_values,
    )
    if scattering is not None:
        material.scattering_wavelengths, material.scattering_values = SHARED_DIFFUSION
        material.scattering = scattering
    return material


def test_non_scattering_material():
    """The article describes an index curve and an absorption curve, and no scattering."""
    material = MaterialFile.load(REFERENCE_DIR / "Non-Scattering.material")

    assert material == material_with()
    assert material.scattering is None
    assert material.material_type == "Isotropic"
    assert material.measured_concentration == 1.0
    assert material.user_concentration == 1.0


def test_henyey_greenstein_material():
    """The article gives a single anisotropy factor of 0.9, valid at every wavelength."""
    material = MaterialFile.load(REFERENCE_DIR / "Henyey-Greenstein.material")

    assert material == material_with(
        VolumeScatteringHenyeyGreenstein(wavelengths=[], anisotropies=[0.9])
    )


def test_double_henyey_greenstein_material():
    """The article gives two anisotropy factors of 0.9 weighted by a ratio of 0.5."""
    material = MaterialFile.load(REFERENCE_DIR / "Double Henyey-Greenstein.material")

    assert material == material_with(
        VolumeScatteringDoubleHenyeyGreenstein(
            wavelengths=[], anisotropies_1=[0.9], anisotropies_2=[0.9], ratios=[0.5]
        )
    )


def test_gegenbauer_material():
    """The article gives an anisotropy factor of 0.9 and an alpha coefficient of 0.5."""
    material = MaterialFile.load(REFERENCE_DIR / "Gegenbauer.material")

    assert material == material_with(
        VolumeScatteringGegenbauer(wavelengths=[], anisotropies=[0.9], alphas=[0.5])
    )


def test_user_defined_material():
    """The article gives a 361 point curve of the efficiency against the scattering angle."""
    material = MaterialFile.load(REFERENCE_DIR / "User-Defined.material")
    phase_function = material.scattering

    assert isinstance(phase_function, VolumeScatteringUserDefined)
    assert phase_function.wavelengths == []
    assert len(phase_function.angles) == 361
    assert phase_function.angles[0] == 0.0
    assert phase_function.angles[-1] == 180.0
    assert phase_function.angles[1] - phase_function.angles[0] == pytest.approx(0.5)
    assert phase_function.values[0] == [100.0]
    assert phase_function.values[1] == [59.344]
    assert phase_function.values[-1] == [0.0]
    assert material == material_with(phase_function)


@pytest.mark.parametrize(
    "file_name",
    [
        "Non-Scattering.material",
        "Henyey-Greenstein.material",
        "Double Henyey-Greenstein.material",
        "Gegenbauer.material",
        "User-Defined.material",
        "Gold.material",
        "Birefringent SellMeier.material",
    ],
)
def test_material_files_are_written_back_unchanged(file_name, tmp_path):
    """Writing a reference material back must reproduce it line for line."""
    reference = REFERENCE_DIR / file_name

    assert_written_back_unchanged(MaterialFile.load(reference), tmp_path, reference)


def test_metallic_material():
    """The gold sample holds 74 points of the complex index, and nothing else."""
    material = MaterialFile.load(REFERENCE_DIR / "Gold.material")
    dispersion = material.dispersion

    assert material.material_type == "Metallic"
    assert isinstance(dispersion, MaterialMetallicCurve)
    assert len(dispersion.wavelengths) == 74
    assert (dispersion.wavelengths[0], dispersion.indices[0], dispersion.extinctions[0]) == (
        247.97,
        1.4943,
        1.9575,
    )
    assert (dispersion.wavelengths[-1], dispersion.indices[-1], dispersion.extinctions[-1]) == (
        807.62,
        0.19129,
        4.7649,
    )
    assert material.absorption_wavelengths == []
    assert material.scattering is None


def test_birefringent_material():
    """The sample is a biaxial material whose three axes share the same coefficients."""
    material = MaterialFile.load(REFERENCE_DIR / "Birefringent SellMeier.material")
    coefficients = MaterialSellmeier(1.03961, 0.0060007, 0.231792, 0.0200179, 1.01047, 103.561)

    assert material.material_type == "Birefringent"
    assert material.dispersion == MaterialBirefringentSellmeier(
        a=coefficients, b=coefficients, c=coefficients, optical_class=2
    )
    assert material.axis_j == [1.0, 0.0, 0.0]
    assert material.axis_k == [0.0, 1.0, 0.0]
    assert material.absorption_wavelengths == [486.0, 532.0, 643.0]
    assert material.absorption_values == [0.0, 0.0, 0.0]
    assert material.absorption_values_b == [0.0, 0.0, 0.0]
    assert material.absorption_values_c == [0.0, 0.0, 0.0]
    assert material.scattering is None


def test_a_single_wavelength_phase_function_must_not_carry_a_wavelength(tmp_path):
    """The reference files show that Speos drops the wavelength for a single factor."""
    with pytest.raises(ValueError, match="leave wavelengths empty"):
        VolumeScatteringHenyeyGreenstein(wavelengths=[550.0], anisotropies=[0.9])


def test_coated_surface():
    """The article gives the P and S responses at 4 incidences and 3 wavelengths."""
    coating = CoatedSurfaceFile.load(REFERENCE_DIR / "Coating Example.coated")

    assert coating.description == "Coating File Example"
    assert coating.wavelengths == [480.0, 580.0, 780.0]
    assert coating.incident_angles == [0.0, 50.0, 70.0, 90.0]
    # The article shows the P and S rows differing at normal and 50 degree incidence.
    assert coating.samples[0][0] == CoatedSurfaceSample(35.0, 65.0, 31.9, 68.1)
    assert coating.samples[1][0] == CoatedSurfaceSample(12.0, 89.0, 11.3, 88.7)
    assert coating.samples[2][2] == CoatedSurfaceSample(26.3, 73.7, 26.3, 73.7)
    assert coating.samples[3][0] == CoatedSurfaceSample(100.0, 0.0, 100.0, 0.0)
    assert coating.samples[0][0].absorption_p == pytest.approx(0.0)
    # At 50 degrees the P row overruns 100 percent while the S row does not.
    assert coating.samples[1][0].absorption_p == pytest.approx(-1.0)
    assert coating.samples[1][0].absorption_s == pytest.approx(0.0)


def test_the_coated_surface_is_written_back_byte_for_byte(tmp_path):
    """Writing the reference coating back must reproduce the original file exactly."""
    reference = REFERENCE_DIR / "Coating Example.coated"
    written = CoatedSurfaceFile.load(reference).save(tmp_path / "copy.coated")

    assert written.read_bytes() == reference.read_bytes()


def test_spectrum():
    """The article gives a 129 point curve digitized from a graph, in nm and percent."""
    spectrum = SpectrumFile.load(REFERENCE_DIR / "KB.spectrum")

    assert spectrum.description == "Example"
    assert len(spectrum.wavelengths) == 129
    assert len(spectrum.values) == 129
    assert spectrum.wavelengths[0] == pytest.approx(402.0303390069588)
    assert spectrum.values[0] == pytest.approx(0.14760318637482328)
    assert spectrum.wavelengths[-1] == pytest.approx(748.1239420725973)
    assert spectrum.values[-1] == pytest.approx(0.693503222176787)
    assert max(spectrum.values) == pytest.approx(99.0049327150391)
    assert all(0.0 <= value <= 100.0 for value in spectrum.values)


def test_the_spectrum_samples_are_written_back_unchanged(tmp_path):
    """Writing the reference spectrum back must reproduce every sample exactly.

    Only the tokens are compared: the file shipped by Ansys separates them with a space
    and misspells its header as ``OPTIS - Spectrum fie v1.0``, while Speos itself writes a
    tabulation and spells the header out.
    """
    reference = REFERENCE_DIR / "KB.spectrum"
    written = SpectrumFile.load(reference).save(tmp_path / "copy.spectrum")

    assert [line.split() for line in read_lines(written)[2:]] == [
        line.split() for line in read_lines(reference)[2:]
    ]


@pytest.mark.parametrize(
    ("file_name", "pattern_count", "first", "last"),
    [
        (
            "GENERIC_CAR 2023R2.3D Texture.1.OPT3DMapping",
            10201,
            TexturePattern(position=(0.0, -0.0, 0.0)),
            TexturePattern(position=(100.0, 100.0, -0.0)),
        ),
        (
            "TL L.3D Texture.2.OPT3DMapping",
            11029,
            TexturePattern(position=(9.0, 6.0, -93.9934), scale=(0.5, 0.5, 1.0)),
            TexturePattern(position=(234.0, 16.0, -89.3451), scale=(0.5, 0.5, 1.0)),
        ),
    ],
)
def test_texture_3d_mapping(file_name, pattern_count, first, last):
    """The article describes a pattern count then one line of 12 values per pattern.

    Those values are the position, the local X and Y directions, and the scale factors
    along X, Y and Z.
    """
    mapping = Texture3DMappingFile.load(REFERENCE_DIR / file_name)

    assert len(mapping.patterns) == pattern_count
    assert mapping.uniform_scale is False
    assert mapping.patterns[0] == first
    assert mapping.patterns[-1] == last


@pytest.mark.parametrize(
    "file_name",
    [
        "GENERIC_CAR 2023R2.3D Texture.1.OPT3DMapping",
        "TL L.3D Texture.2.OPT3DMapping",
    ],
)
def test_the_texture_3d_mappings_are_written_back_byte_for_byte(file_name, tmp_path):
    """Writing a mapping generated by Speos back must reproduce the original file."""
    reference = REFERENCE_DIR / file_name
    written = Texture3DMappingFile.load(reference).save(tmp_path / file_name)

    assert written.read_bytes() == reference.read_bytes()


@pytest.mark.parametrize(
    "model_class",
    (
        CoatedSurfaceFile,
        CoatedSurfaceSample,
        Ray,
        RayFile,
        ScatteringSurfaceFile,
        ScatteringSurfaceSample,
        SimpleScatteringSurfaceFile,
        SpectrumFile,
        Texture3DMappingFile,
        TexturePattern,
        *MaterialFile.DISPERSIONS,
        MaterialMetallicCurve,
        *MaterialFile.BIREFRINGENT_DISPERSIONS,
        *MaterialFile.SCATTERINGS,
        MaterialFile,
    ),
)
def test_models_share_the_explicit_equality_contract(model_class):
    """Every model declares its fields and inherits strict, unhashable value equality."""
    model, other = model_class(), model_class()
    assert model._EQUALITY_FIELDS
    assert set(model._EQUALITY_FIELDS) == set(signature(model_class).parameters)
    for name in model._EQUALITY_FIELDS:
        attribute = getattr(model_class, name)
        assert isinstance(attribute, property)
        assert _property_name(attribute) == name
    assert model_class.__eq__ is _ValueComparable.__eq__
    assert model == other
    assert model.__eq__(object()) is NotImplemented
    assert model != object()
    with pytest.raises(TypeError):
        hash(model)

    derived_class = type(f"Derived{model_class.__name__}", (model_class,), {})
    derived = derived_class()
    assert model.__eq__(derived) is NotImplemented
    assert derived.__eq__(model) is NotImplemented
    assert model != derived
    assert derived == derived_class()


def test_property_names_follow_named_getter_symbols():
    """A field inventory uses the actual getter symbol rather than a repeated name string."""

    class RenamedModel(_ValueComparable):
        """Model with a named property used directly in its field inventory."""

        @property
        def renamed_value(self) -> float:
            """Return the sample value."""
            return 1.0

        _EQUALITY_FIELDS = (_property_name(renamed_value),)

    assert RenamedModel._EQUALITY_FIELDS == ("renamed_value",)
    assert RenamedModel() == RenamedModel()


def test_property_names_require_a_getter():
    """A write-only property cannot supply a getter name."""
    attribute = property(fset=lambda instance, value: None)
    with pytest.raises(ValueError, match="must have a getter"):
        _property_name(attribute)


@pytest.mark.parametrize("attribute", (object(), "reflection_p", 1.0))
def test_property_names_reject_nonproperty_inputs(attribute):
    """The property-name helper rejects values that are not property descriptors."""
    with pytest.raises(TypeError, match="property descriptor"):
        _property_name(attribute)


def test_equality_mixin_requires_declared_fields():
    """Missing field declarations fail rather than treating arbitrary models as equal."""

    class UndeclaredModel(_ValueComparable):
        """Model deliberately missing its equality field declaration."""

    with pytest.raises(AttributeError, match="_EQUALITY_FIELDS"):
        UndeclaredModel() == UndeclaredModel()


def test_shared_equality_observes_nested_model_changes():
    """Nested coefficient and ray edits remain visible through parent model equality."""
    material, other_material = MaterialFile(), MaterialFile()
    assert material == other_material
    material.dispersion.index = 1.6
    assert material != other_material

    birefringent, other_birefringent = (
        MaterialBirefringentSellmeier(),
        MaterialBirefringentSellmeier(),
    )
    assert birefringent == other_birefringent
    birefringent.b.b1 = 1.0
    assert birefringent != other_birefringent

    rays, other_rays = RayFile([Ray()]), RayFile([Ray()])
    assert rays == other_rays
    rays.rays[0].energy = 0.5
    assert rays != other_rays


def test_standalone_models_do_not_inherit_file_io():
    """The equality mixin does not expose file I/O on standalone nested models."""
    for model_class in (
        Ray,
        TexturePattern,
        CoatedSurfaceSample,
        ScatteringSurfaceSample,
        *MaterialFile.DISPERSIONS,
        *MaterialFile.SCATTERINGS,
    ):
        assert issubclass(model_class, _ValueComparable)
        assert not issubclass(model_class, SpeosFileFormat)
        assert not hasattr(model_class, "save")
