# Copyright (C) 2021 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Check the file formats against the reference files published by Ansys.

Round-trip tests cannot catch a mistake made symmetrically in the reader and in the
writer. The files in ``tests/assets/input_files`` were produced by Speos and attached to
the Ansys Optics knowledge base articles describing each format, so they pin the layout
independently from our own implementation:

* ``Non-Scattering.material``, ``Henyey-Greenstein.material``,
  ``Double Henyey-Greenstein.material``, ``Gegenbauer.material`` and
  ``User-Defined.material`` come from the Speos Scattering and Non-Scattering Volume
  Format articles.
* ``Coating Example.coated`` comes from the Speos Coating Surface Format article.
* ``KB.spectrum`` comes from the Create spectrum file from graph article.
* the two ``*.OPT3DMapping`` files come from the ``3DTexture_Data.7z`` archive of the
  Homogeneous 3D Texture via Scripting article, and were generated by Speos itself.

Each test states what the article says the file holds, then checks that reading it gives
exactly that, and that writing the model back reproduces the original lines.
"""

import pytest

from ansys.speos.core import (
    CoatedSurfaceFile,
    CoatedSurfaceSample,
    MaterialDispersionCurve,
    MaterialFile,
    SpectrumFile,
    Texture3DMappingFile,
    TexturePattern,
    VolumeScatteringDoubleHenyeyGreenstein,
    VolumeScatteringGegenbauer,
    VolumeScatteringHenyeyGreenstein,
    VolumeScatteringUserDefined,
)
from tests.input_files import ASSETS_DIR, read_lines

REFERENCE_DIR = ASSETS_DIR / "input_files"
"""Directory holding the reference files attached to the knowledge base articles."""

SHARED_DISPERSION = MaterialDispersionCurve(
    wavelengths=[486.0, 532.0, 643.0], indices=[2.0, 1.5, 1.2]
)
"""Index curve shared by every reference material file."""

SHARED_ABSORPTION = ([400.0, 550.0, 700.0], [0.1, 0.2, 0.01])
"""Absorption curve shared by every reference material file, in nm and mm-1."""

SHARED_DIFFUSION = ([486.0, 532.0, 643.0], [0.016813, 7.3952e-17, 0.017344])
"""Diffusion curve shared by every scattering reference material file, in nm and mm-1."""


def normalize(line):
    """Drop the ``.0`` that some Speos versions append to a format version.

    The samples attached to the articles are stamped ``OPTIS - Material file v13.0`` and
    ``OPTIS - Volumic Scattering file v1.0``, while the 2026 R1 User Material editor
    writes ``v13`` and ``v1`` for the very same content.
    """
    stripped = line.rstrip()
    if stripped.startswith("OPTIS - ") and stripped.endswith(".0"):
        return stripped[:-2]
    return stripped


def assert_written_back_unchanged(model, tmp_path, reference):
    """Check that writing the model reproduces the lines of the reference file.

    Blank lines, trailing whitespace and the format version are ignored, since Speos is
    not consistent about any of them.
    """
    written = model.save(tmp_path / reference.name)
    expected = [normalize(line) for line in read_lines(reference) if line.strip()]
    actual = [normalize(line) for line in read_lines(written) if line.strip()]

    assert actual == expected


def material_with(scattering=None):
    """Build the reference material, optionally carrying a scattering phase function."""
    absorption_wavelengths, absorption_values = SHARED_ABSORPTION
    description = "Example file to understand Speos {} file structure".format(
        "scattering" if scattering else "non-scattering"
    )
    material = MaterialFile(
        description=description,
        dispersion=SHARED_DISPERSION,
        absorption_wavelengths=absorption_wavelengths,
        absorption_values=absorption_values,
    )
    if scattering is not None:
        material.scattering_wavelengths, material.scattering_values = SHARED_DIFFUSION
        material.scattering = scattering
    return material


def test_non_scattering_material():
    """The article describes an index curve and an absorption curve, and no scattering."""
    material = MaterialFile.load(REFERENCE_DIR / "Non-Scattering.material")

    assert material == material_with()
    assert material.scattering is None
    assert material.material_type == "Isotropic"
    assert material.measured_concentration == 1.0
    assert material.user_concentration == 1.0


def test_henyey_greenstein_material():
    """The article gives a single anisotropy factor of 0.9, valid at every wavelength."""
    material = MaterialFile.load(REFERENCE_DIR / "Henyey-Greenstein.material")

    assert material == material_with(
        VolumeScatteringHenyeyGreenstein(wavelengths=[], anisotropies=[0.9])
    )


def test_double_henyey_greenstein_material():
    """The article gives two anisotropy factors of 0.9 weighted by a ratio of 0.5."""
    material = MaterialFile.load(REFERENCE_DIR / "Double Henyey-Greenstein.material")

    assert material == material_with(
        VolumeScatteringDoubleHenyeyGreenstein(
            wavelengths=[], anisotropies_1=[0.9], anisotropies_2=[0.9], ratios=[0.5]
        )
    )


def test_gegenbauer_material():
    """The article gives an anisotropy factor of 0.9 and an alpha coefficient of 0.5."""
    material = MaterialFile.load(REFERENCE_DIR / "Gegenbauer.material")

    assert material == material_with(
        VolumeScatteringGegenbauer(wavelengths=[], anisotropies=[0.9], alphas=[0.5])
    )


def test_user_defined_material():
    """The article gives a 361 point curve of the efficiency against the scattering angle."""
    material = MaterialFile.load(REFERENCE_DIR / "User-Defined.material")
    phase_function = material.scattering

    assert isinstance(phase_function, VolumeScatteringUserDefined)
    assert phase_function.wavelengths == []
    assert len(phase_function.angles) == 361
    assert phase_function.angles[0] == 0.0
    assert phase_function.angles[-1] == 180.0
    assert phase_function.angles[1] - phase_function.angles[0] == pytest.approx(0.5)
    assert phase_function.values[0] == [100.0]
    assert phase_function.values[1] == [59.344]
    assert phase_function.values[-1] == [0.0]
    assert material == material_with(phase_function)


@pytest.mark.parametrize(
    "file_name",
    [
        "Non-Scattering.material",
        "Henyey-Greenstein.material",
        "Double Henyey-Greenstein.material",
        "Gegenbauer.material",
        "User-Defined.material",
    ],
)
def test_material_files_are_written_back_unchanged(file_name, tmp_path):
    """Writing a reference material back must reproduce it line for line."""
    reference = REFERENCE_DIR / file_name

    assert_written_back_unchanged(MaterialFile.load(reference), tmp_path, reference)


def test_a_single_wavelength_phase_function_must_not_carry_a_wavelength(tmp_path):
    """The reference files show that Speos drops the wavelength for a single factor."""
    material = material_with(
        VolumeScatteringHenyeyGreenstein(wavelengths=[550.0], anisotropies=[0.9])
    )

    with pytest.raises(ValueError, match="leave wavelengths empty"):
        material.save(tmp_path / "invalid.material")


def test_coated_surface():
    """The article gives the P and S responses at 4 incidences and 3 wavelengths."""
    coating = CoatedSurfaceFile.load(REFERENCE_DIR / "Coating Example.coated")

    assert coating.description == "Coating File Example"
    assert coating.wavelengths == [480.0, 580.0, 780.0]
    assert coating.incident_angles == [0.0, 50.0, 70.0, 90.0]
    # The article shows the P and S rows differing at normal and 50 degree incidence.
    assert coating.samples[0][0] == CoatedSurfaceSample(35.0, 65.0, 31.9, 68.1)
    assert coating.samples[1][0] == CoatedSurfaceSample(12.0, 89.0, 11.3, 88.7)
    assert coating.samples[2][2] == CoatedSurfaceSample(26.3, 73.7, 26.3, 73.7)
    assert coating.samples[3][0] == CoatedSurfaceSample(100.0, 0.0, 100.0, 0.0)
    assert coating.samples[0][0].absorption_p == pytest.approx(0.0)
    # At 50 degrees the P row overruns 100 percent while the S row does not.
    assert coating.samples[1][0].absorption_p == pytest.approx(-1.0)
    assert coating.samples[1][0].absorption_s == pytest.approx(0.0)


def test_the_coated_surface_is_written_back_byte_for_byte(tmp_path):
    """Writing the reference coating back must reproduce the original file exactly."""
    reference = REFERENCE_DIR / "Coating Example.coated"
    written = CoatedSurfaceFile.load(reference).save(tmp_path / "copy.coated")

    assert written.read_bytes() == reference.read_bytes()


def test_spectrum():
    """The article gives a 129 point curve digitized from a graph, in nm and percent."""
    spectrum = SpectrumFile.load(REFERENCE_DIR / "KB.spectrum")

    assert spectrum.description == "Example"
    assert len(spectrum.wavelengths) == 129
    assert len(spectrum.values) == 129
    assert spectrum.wavelengths[0] == pytest.approx(402.0303390069588)
    assert spectrum.values[0] == pytest.approx(0.14760318637482328)
    assert spectrum.wavelengths[-1] == pytest.approx(748.1239420725973)
    assert spectrum.values[-1] == pytest.approx(0.693503222176787)
    assert max(spectrum.values) == pytest.approx(99.0049327150391)
    assert all(0.0 <= value <= 100.0 for value in spectrum.values)


def test_the_spectrum_samples_are_written_back_unchanged(tmp_path):
    """Writing the reference spectrum back must reproduce every sample exactly.

    Only the tokens are compared: the file shipped by Ansys separates them with a space
    and misspells its header as ``OPTIS - Spectrum fie v1.0``, while Speos itself writes a
    tabulation and spells the header out.
    """
    reference = REFERENCE_DIR / "KB.spectrum"
    written = SpectrumFile.load(reference).save(tmp_path / "copy.spectrum")

    assert [line.split() for line in read_lines(written)[2:]] == [
        line.split() for line in read_lines(reference)[2:]
    ]


@pytest.mark.parametrize(
    ("file_name", "pattern_count", "first", "last"),
    [
        (
            "GENERIC_CAR 2023R2.3D Texture.1.OPT3DMapping",
            10201,
            TexturePattern(position=(0.0, -0.0, 0.0)),
            TexturePattern(position=(100.0, 100.0, -0.0)),
        ),
        (
            "TL L.3D Texture.2.OPT3DMapping",
            11029,
            TexturePattern(position=(9.0, 6.0, -93.9934), scale=(0.5, 0.5, 1.0)),
            TexturePattern(position=(234.0, 16.0, -89.3451), scale=(0.5, 0.5, 1.0)),
        ),
    ],
)
def test_texture_3d_mapping(file_name, pattern_count, first, last):
    """The article describes a pattern count then one line of 12 values per pattern.

    Those values are the position, the local X and Y directions, and the scale factors
    along X, Y and Z.
    """
    mapping = Texture3DMappingFile.load(REFERENCE_DIR / file_name)

    assert len(mapping.patterns) == pattern_count
    assert mapping.uniform_scale is False
    assert mapping.patterns[0] == first
    assert mapping.patterns[-1] == last


@pytest.mark.parametrize(
    "file_name",
    [
        "GENERIC_CAR 2023R2.3D Texture.1.OPT3DMapping",
        "TL L.3D Texture.2.OPT3DMapping",
    ],
)
def test_the_texture_3d_mappings_are_written_back_byte_for_byte(file_name, tmp_path):
    """Writing a mapping generated by Speos back must reproduce the original file."""
    reference = REFERENCE_DIR / file_name
    written = Texture3DMappingFile.load(reference).save(tmp_path / file_name)

    assert written.read_bytes() == reference.read_bytes()
